import {
  buildRecommendRelationshipsSavePayload,
  buildRecommendRelationshipsViewState,
  hasRecommendRelationshipsResult,
} from './recommendRelationshipsSupport';
import type { RelationshipRecommendationTaskResponse } from '@/types/modelingAssistant';
import { RelationType } from '@/types/modeling';

const models = [
  {
    id: 1,
    displayName: 'Resume Translations',
    referenceName: 'xai_hr.resume_translations',
    sourceTableName: 'resume_translations',
    cached: false,
    fields: [
      {
        id: 11,
        displayName: 'reviewed_by',
        referenceName: 'reviewed_by',
        sourceColumnName: 'reviewed_by',
        isCalculated: false,
        notNull: false,
      },
    ],
    calculatedFields: [],
  },
  {
    id: 2,
    displayName: 'Auth Users',
    referenceName: 'xai_hr.auth_users',
    sourceTableName: 'auth_users',
    cached: false,
    fields: [
      {
        id: 21,
        displayName: 'id',
        referenceName: 'id',
        sourceColumnName: 'id',
        isCalculated: false,
        notNull: true,
      },
    ],
    calculatedFields: [],
  },
] as any;

describe('recommendRelationshipsSupport', () => {
  it('maps task results into grouped relation draft state', () => {
    const task: RelationshipRecommendationTaskResponse = {
      id: 'task-1',
      status: 'FINISHED',
      response: {
        relationships: [
          {
            name: 'ReviewedByAuthUser',
            fromModel: 'xai_hr.resume_translations',
            fromColumn: 'reviewed_by',
            toModel: 'xai_hr.auth_users',
            toColumn: 'id',
            type: RelationType.MANY_TO_ONE,
            reason: 'Connect reviewer to auth user',
          },
        ],
      },
      error: null,
    };

    const result = buildRecommendRelationshipsViewState({ models, task });

    expect(result.recommendNameMapping['xai_hr.resume_translations']).toBe(
      'Resume Translations',
    );
    expect(
      result.recommendRelations['xai_hr.resume_translations'],
    ).toHaveLength(1);
    expect(
      result.recommendRelations['xai_hr.resume_translations'][0],
    ).toMatchObject({
      type: RelationType.MANY_TO_ONE,
      properties: { description: 'Connect reviewer to auth user' },
    });
    expect(hasRecommendRelationshipsResult(result.recommendRelations)).toBe(
      true,
    );
  });

  it('builds save payload with optional description', () => {
    const payload = buildRecommendRelationshipsSavePayload({
      'xai_hr.resume_translations': [
        {
          name: 'ReviewedByAuthUser',
          fromField: {
            modelId: '1',
            modelName: 'xai_hr.resume_translations',
            fieldId: '11',
            fieldName: 'reviewed_by',
          },
          toField: {
            modelId: '2',
            modelName: 'xai_hr.auth_users',
            fieldId: '21',
            fieldName: 'id',
          },
          type: RelationType.MANY_TO_ONE,
          isAutoGenerated: true,
          properties: { description: 'Connect reviewer to auth user' },
        },
      ],
    } as any);

    expect(payload).toEqual([
      {
        fromModelId: 1,
        fromColumnId: 11,
        toModelId: 2,
        toColumnId: 21,
        type: 'MANY_TO_ONE',
        description: 'Connect reviewer to auth user',
      },
    ]);
  });
});
