import type { ModelListItem } from '@/hooks/useModelList';
import type { SelectedRecommendRelations } from '@/components/pages/setup/DefineRelations';
import type { RelationInput } from '@/types/modeling';
import type {
  RelationshipRecommendationSavePayload,
  RelationshipRecommendationTaskResponse,
} from '@/types/modelingAssistant';

export type RecommendRelationshipsViewState = {
  recommendRelations: SelectedRecommendRelations;
  recommendNameMapping: Record<string, string>;
};

const findFieldCandidates = (model: ModelListItem) =>
  [...(model.fields || []), ...(model.calculatedFields || [])].filter(
    (field): field is NonNullable<(typeof model.fields)[number]> =>
      Boolean(field),
  );

export const buildRecommendRelationshipsViewState = ({
  models,
  task,
}: {
  models: ModelListItem[];
  task?: RelationshipRecommendationTaskResponse | null;
}): RecommendRelationshipsViewState => {
  const modelMap = new Map(models.map((model) => [model.referenceName, model]));
  const recommendRelations: SelectedRecommendRelations = {};
  const recommendNameMapping: Record<string, string> = {};

  (task?.response?.relationships || []).forEach((relationship) => {
    const fromModel = modelMap.get(relationship.fromModel);
    const toModel = modelMap.get(relationship.toModel);
    if (!fromModel || !toModel) {
      return;
    }

    const fromField = findFieldCandidates(fromModel).find(
      (field) => field.referenceName === relationship.fromColumn,
    );
    const toField = findFieldCandidates(toModel).find(
      (field) => field.referenceName === relationship.toColumn,
    );

    if (!fromField || !toField) {
      return;
    }

    recommendRelations[fromModel.referenceName] = [
      ...(recommendRelations[fromModel.referenceName] || []),
      {
        name: relationship.name,
        fromField: {
          modelId: String(fromModel.id),
          modelName: fromModel.referenceName,
          fieldId: String(fromField.id),
          fieldName: fromField.referenceName,
        },
        toField: {
          modelId: String(toModel.id),
          modelName: toModel.referenceName,
          fieldId: String(toField.id),
          fieldName: toField.referenceName,
        },
        type: relationship.type,
        isAutoGenerated: true,
        properties: relationship.reason
          ? { description: relationship.reason }
          : {},
      },
    ];
    recommendNameMapping[fromModel.referenceName] = fromModel.displayName;
  });

  return {
    recommendRelations,
    recommendNameMapping,
  };
};

export const hasRecommendRelationshipsResult = (
  relations: SelectedRecommendRelations,
) =>
  Object.values(relations).some(
    (modelRelations) =>
      Array.isArray(modelRelations) && modelRelations.length > 0,
  );

export const buildRecommendRelationshipsSavePayload = (
  relations: SelectedRecommendRelations,
): RelationshipRecommendationSavePayload[] =>
  Object.values(relations).flatMap((modelRelations) =>
    modelRelations.map((relation) => ({
      fromModelId: Number(relation.fromField.modelId),
      fromColumnId: Number(relation.fromField.fieldId),
      toModelId: Number(relation.toField.modelId),
      toColumnId: Number(relation.toField.fieldId),
      type: relation.type as RelationInput['type'],
      description:
        typeof relation.properties?.description === 'string'
          ? relation.properties.description
          : undefined,
    })),
  );
