apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wren-ai.fullname" . }}-ibis-server
  labels:
    {{- include "wren-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: ibis-server
spec:
  replicas: {{ default 1 .Values.ibisServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "wren-ai.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ibis-server
  template:
    metadata:
      labels:
        {{- include "wren-ai.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ibis-server
    spec:
      {{- with .Values.ibisServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ibisServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ibisServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: wren-ibis
          image: "{{ .Values.ibisServer.image.repository }}:{{ .Values.ibisServer.image.tag | default .Values.global.versions.ibisServer }}"
          imagePullPolicy: {{ .Values.ibisServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ibisServer.service.port }}
              protocol: TCP
          env:
            - name: WREN_ENGINE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wren-ai.fullname" . }}-config
                  key: WREN_ENGINE_ENDPOINT
            - name: LOGGING_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wren-ai.fullname" . }}-config
                  key: LOGGING_LEVEL
          {{- with .Values.ibisServer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}