version: '3.8'

networks:
  wren:
    driver: bridge

services:
  wren-engine:
    image: ghcr.io/canner/wren-engine:latest
    pull_policy: always
    platform: ${PLATFORM}
    ports:
      - 8080:8080
      - 7432:7432
    volumes:
      - ./etc:/usr/src/app/etc
      - ${LAUNCH_CLI_PATH}:/usr/src/app/launch-cli.sh
