export enum DATA_SOURCES {
  BIG_QUERY = 'BIG_QUERY',
  DUCKDB = 'DUCKDB',
  PG_SQL = 'POSTGRES',
  MYSQL = 'MYSQL',
  MSSQL = 'MSSQL',
  CLICK_HOUSE = 'CLICK_HOUSE',
  TRINO = 'TRINO',
  SNOWFLAKE = 'SNOWFLAKE',
}
