export enum Path {
  Home = '/home',
  HomeDashboard = '/home/dashboard',
  Thread = '/home/[id]',
  Modeling = '/modeling',
  Onboarding = '/setup',
  OnboardingConnection = '/setup/connection',
  OnboardingModels = '/setup/models',
  OnboardingRelationships = '/setup/relationships',
  Knowledge = '/knowledge',
  KnowledgeQuestionSQLPairs = '/knowledge/question-sql-pairs',
  KnowledgeInstructions = '/knowledge/instructions',
  APIManagement = '/api-management',
  APIManagementHistory = '/api-management/history',
  Administration = '/administration',
  AdministrationUsers = '/administration/users',
  AdministrationRoles = '/administration/roles',
  AdministrationAssignments = '/administration/assignments',
  Organization = '/organization',
  OrganizationGeneral = '/organization/general',
  OrganizationMembers = '/organization/members',
  OrganizationDangerZone = '/organization/danger-zone',
  ProjectCreate = '/projects/create',
}
