import type { RelationType } from './modeling';

export type CompactColumn = {
  name: string;
  properties?: unknown;
  type: string;
};

export type CompactTable = {
  columns: CompactColumn[];
  name: string;
  properties?: unknown;
};

export type DataSource = {
  properties: unknown;
  sampleDataset?: SampleDatasetName | null;
  type: DataSourceName;
};

export enum DataSourceName {
  ATHENA = 'ATHENA',
  BIG_QUERY = 'BIG_QUERY',
  CLICK_HOUSE = 'CLICK_HOUSE',
  DATABRICKS = 'DATABRICKS',
  DUCKDB = 'DUCKDB',
  MSSQL = 'MSSQL',
  MYSQL = 'MYSQL',
  ORACLE = 'ORACLE',
  POSTGRES = 'POSTGRES',
  REDSHIFT = 'REDSHIFT',
  SNOWFLAKE = 'SNOWFLAKE',
  TRINO = 'TRINO',
}

export enum DatabricksConnectionType {
  service_principal = 'service_principal',
  token = 'token',
}

export type ConnectionTablesResult = CompactTable[];

export type Relation = {
  fromColumnId: number;
  fromColumnReferenceName: string;
  fromModelId: number;
  fromModelReferenceName: string;
  name: string;
  toColumnId: number;
  toColumnReferenceName: string;
  toModelId: number;
  toModelReferenceName: string;
  type: RelationType;
};

export type RecommendRelations = {
  displayName: string;
  id: number;
  referenceName: string;
  relations: Array<Relation | null>;
};

export type AutoGeneratedRelationsResponse = {
  autoGenerateRelation: RecommendRelations[];
};

export enum SampleDatasetName {
  ECOMMERCE = 'ECOMMERCE',
  HR = 'HR',
  MUSIC = 'MUSIC',
  NBA = 'NBA',
}

export enum RedshiftConnectionType {
  redshift = 'redshift',
  redshift_iam = 'redshift_iam',
}
