{{/* Create configMaps from .env files (convert key=value to key: value) */}}
{{- range $dotenv := .Values.configMaps.dotenv }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $dotenv.name }}
  labels: {{- include "application.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "-3"
    checksum/config: {{ (tpl ($.Files.Glob $dotenv.path).AsConfig $ ) | sha256sum }}
  namespace: {{ $.Release.Namespace }}
data:
{{- range $.Files.Lines $dotenv.path }}
  {{- if . }}
  {{ (splitList "=" . | first ) }}: {{ (splitList "=" . | rest | join "=") | trim | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{/* Create configMaps from files */}}
{{- range $file := .Values.configMaps.files }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $file.name }}
  labels: {{- include "application.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "-3"
    checksum/config: {{ (tpl ($.Files.Glob $file.path).AsConfig $ ) | sha256sum }}
  namespace: {{ $.Release.Namespace }}
data:
{{ ($.Files.Glob $file.path).AsConfig | indent 2 }}
{{- end }}
