import { buildKnowledgeWorkbenchPageStage } from './buildKnowledgeWorkbenchPageStage';

describe('buildKnowledgeWorkbenchPageStage', () => {
  it('assembles sidebar/main-stage/overlay props and injects readonly hint', () => {
    const result = buildKnowledgeWorkbenchPageStage({
      sidebar: {
        knowledgeTab: 'workspace',
        onChangeKnowledgeTab: jest.fn(),
        visibleKnowledgeItems: [],
        visibleKnowledgeBaseId: 'kb-1',
        activeKnowledgeBaseId: 'kb-1',
        activeAssetCount: 2,
        switchKnowledgeBase: jest.fn(),
        buildKnowledgeSwitchUrl: jest.fn(() => '/knowledge'),
        canCreateKnowledgeBase: true,
        createKnowledgeBaseBlockedReason: '',
        onCreateKnowledgeBase: jest.fn(),
      },
      mainStage: {
        activeWorkbenchSection: 'overview',
        onChangeWorkbenchSection: jest.fn(),
        previewFieldCount: 3,
        isSnapshotReadonlyKnowledgeBase: false,
        isReadonlyKnowledgeBase: false,
        isKnowledgeMutationDisabled: false,
        knowledgeMutationHint: null,
        knowledgeDescription: 'demo',
        showKnowledgeAssetsLoading: false,
        detailAssets: [],
        activeDetailAsset: null,
        detailTab: 'overview',
        detailFieldKeyword: '',
        detailFieldFilter: 'all',
        detailAssetFields: [],
        onOpenAssetWizard: jest.fn(),
        onOpenKnowledgeEditor: jest.fn(),
        onOpenAssetDetail: jest.fn(),
        onCloseAssetDetail: jest.fn(),
        onChangeDetailTab: jest.fn(),
        onChangeFieldKeyword: jest.fn(),
        onChangeFieldFilter: jest.fn(),
        ruleList: [],
        sqlList: [],
        ruleManageLoading: false,
        sqlManageLoading: false,
        onOpenRuleDetail: jest.fn(),
        onOpenSqlTemplateDetail: jest.fn(),
        onDeleteRule: jest.fn(),
        onDeleteSqlTemplate: jest.fn(),
        editingInstruction: null,
        editingSqlPair: null,
        ruleForm: {} as any,
        sqlTemplateForm: {} as any,
        createInstructionLoading: false,
        updateInstructionLoading: false,
        createSqlPairLoading: false,
        updateSqlPairLoading: false,
        onSubmitRuleDetail: jest.fn(),
        onSubmitSqlTemplateDetail: jest.fn(),
        onResetRuleDetailEditor: jest.fn(),
        onResetSqlTemplateEditor: jest.fn(),
        modelingWorkspaceKey: 'key',
        modelingSummary: { modelCount: 1, viewCount: 0, relationCount: 0 },
        onOpenModeling: jest.fn(),
      },
      overlays: {
        knowledgeBaseModalProps: {
          visible: true,
          editingKnowledgeBase: null,
          form: {} as any,
          canSaveKnowledgeBase: true,
          creatingKnowledgeBase: false,
          onCancel: jest.fn(),
          onSave: jest.fn(),
        },
        assetWizardModalProps: {
          visible: false,
          assetWizardStep: 0,
          onChangeAssetWizardStep: jest.fn(),
          activeKnowledgeBase: null,
          knowledgeBases: [],
          sourceOptions: [],
          selectedSourceType: 'database',
          setSelectedSourceType: jest.fn(),
          openConnectorConsole: jest.fn(),
          isDemoSource: false,
          connectorsLoading: false,
          selectedDemoKnowledge: null,
          selectedConnectorId: undefined,
          setSelectedConnectorId: jest.fn(),
          selectedDemoTable: undefined,
          setSelectedDemoTable: jest.fn(),
          assetDatabaseOptions: [],
          assetTableOptions: [],
          canContinueAssetWizard: false,
          moveAssetWizardToConfig: jest.fn(),
          assetDraft: { name: '', description: '', important: true },
          setAssetDraft: jest.fn(),
          assetDraftPreview: null,
          assetDraftPreviews: [],
          canContinueAssetConfiguration: false,
          commitAssetDraftToOverview: jest.fn(),
          savingAssetDraft: false,
          displayKnowledgeName: 'KB',
          closeAssetModal: jest.fn(),
          onNavigateModeling: jest.fn(),
        },
      },
    });

    expect(result.sidebarProps.activeKnowledgeBaseId).toBe('kb-1');
    expect(result.mainStageProps.historicalSnapshotReadonlyHint).toBeTruthy();
    expect(result.overlaysProps.knowledgeBaseModalProps?.visible).toBe(true);
  });
});
