import useKnowledgeWorkbenchPresentationState from './useKnowledgeWorkbenchPresentationState';
import type { ConnectorView, KnowledgeBaseRecord } from './types';
import type { KnowledgeWorkbenchViewStateArgs } from './knowledgeWorkbenchViewStateTypes';

export function buildKnowledgeWorkbenchPresentationStateInputs<
  TKnowledgeBase extends KnowledgeBaseRecord,
  TConnector extends ConnectorView,
>({
  activeKnowledgeBase,
  activeKnowledgeBaseExecutable,
  activeKnowledgeRuntimeSelector,
  assetDraft,
  assets,
  buildKnowledgeRuntimeSelector,
  buildRuntimeScopeUrl,
  connectors,
  demoDatabaseOptions,
  demoTableOptions,
  detailAsset,
  detailFieldFilter,
  detailFieldKeyword,
  diagramData,
  diagramLoading,
  isDemoSource,
  knowledgeBases,
  knowledgeOwner,
  knowledgeTab,
  openAssetWizard,
  overviewPreviewAsset,
  refetchDiagram,
  pendingKnowledgeBaseId,
  replaceWorkspace,
  resetDetailViewState,
  routeRuntimeSyncing,
  routerQuery,
  selectedConnectorId,
  selectedDemoKnowledge,
  selectedDemoTable,
  setAssetDraft,
  setAssetWizardStep,
  setDetailAsset,
  setDraftAssets,
}: KnowledgeWorkbenchViewStateArgs<TKnowledgeBase, TConnector>): Parameters<
  typeof useKnowledgeWorkbenchPresentationState<TKnowledgeBase, TConnector>
>[0] {
  return {
    activeKnowledgeBase,
    activeKnowledgeBaseExecutable,
    activeKnowledgeRuntimeSelector,
    assetDraft,
    assets,
    buildKnowledgeRuntimeSelector,
    buildRuntimeScopeUrl,
    connectors,
    demoDatabaseOptions,
    demoTableOptions,
    detailAsset,
    detailFieldFilter,
    detailFieldKeyword,
    diagramData,
    diagramLoading,
    isDemoSource,
    knowledgeBases,
    knowledgeOwner,
    knowledgeTab,
    openAssetWizard,
    overviewPreviewAsset,
    refetchDiagram,
    pendingKnowledgeBaseId,
    replaceWorkspace,
    resetDetailViewState,
    routeRuntimeSyncing,
    routerQuery,
    selectedConnectorId,
    selectedDemoKnowledge,
    selectedDemoTable,
    setAssetDraft,
    setAssetWizardStep,
    setDetailAsset,
    setDraftAssets,
  };
}

export default buildKnowledgeWorkbenchPresentationStateInputs;
