models:
- api_base: https://api.openai.com/v1
  api_key_name: LLM_OPENAI_API_KEY
  kwargs:
    max_tokens: 4096
    n: 1
    seed: 0
    temperature: 0
  model: gpt-4o-mini-2024-07-18
- api_base: https://api.openai.com/v1
  api_key_name: LLM_OPENAI_API_KEY
  kwargs:
    max_tokens: 4096
    n: 1
    seed: 0
    temperature: 0
  model: gpt-4o-2024-08-06
provider: litellm_llm
timeout: 120
type: llm
---
api_base: https://api.openai.com/v1
models:
- model: text-embedding-3-large
provider: openai_embedder
timeout: 120
type: embedder
---
endpoint: http://localhost:3001
provider: wren_ui
type: engine
---
connection_info: ''
endpoint: http://localhost:8000
manifest: ''
provider: wren_ibis
source: bigquery
type: engine
---
endpoint: http://localhost:8080
manifest: ''
provider: wren_engine
type: engine
---
embedding_model_dim: 3072
location: http://localhost:6333
provider: qdrant
recreate_index: false
timeout: 120
type: document_store
---
pipes:
- document_store: qdrant
  embedder: openai_embedder.text-embedding-3-large
  name: db_schema_indexing
- document_store: qdrant
  embedder: openai_embedder.text-embedding-3-large
  name: historical_question_indexing
- document_store: qdrant
  embedder: openai_embedder.text-embedding-3-large
  name: table_description_indexing
- document_store: qdrant
  embedder: openai_embedder.text-embedding-3-large
  llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: db_schema_retrieval
- document_store: qdrant
  embedder: openai_embedder.text-embedding-3-large
  name: historical_question_retrieval
- engine: wren_ui
  llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: sql_generation
- engine: wren_ui
  llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: sql_correction
- engine: wren_ui
  llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: followup_sql_generation
- llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: sql_summary
- engine: wren_ui
  llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: sql_answer
- engine: wren_ui
  llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: sql_breakdown
- engine: wren_ui
  llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: sql_expansion
- llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: sql_explanation
- engine: wren_ui
  llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: sql_regeneration
- llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: semantics_description
- engine: wren_ui
  llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: relationship_recommendation
- llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: question_recommendation
- document_store: qdrant
  embedder: openai_embedder.text-embedding-3-large
  llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: question_recommendation_db_schema_retrieval
- engine: wren_ui
  llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: question_recommendation_sql_generation
- llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: chart_generation
- llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: chart_adjustment
- document_store: qdrant
  embedder: openai_embedder.text-embedding-3-large
  llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: intent_classification
- llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: data_assistance
- document_store: qdrant
  embedder: openai_embedder.text-embedding-3-large
  name: sql_pairs_indexing
- document_store: qdrant
  embedder: openai_embedder.text-embedding-3-large
  name: sql_pairs_deletion
- document_store: qdrant
  embedder: openai_embedder.text-embedding-3-large
  llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: sql_pairs_retrieval
- llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: preprocess_sql_data
- engine: wren_ui
  name: sql_executor
- llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: sql_question_generation
- llm: litellm_llm.gpt-4o-mini-2024-07-18
  name: sql_generation_reasoning
type: pipeline
---
settings:
  allow_using_db_schemas_without_pruning: false
  column_indexing_batch_size: 50
  development: true
  host: 127.0.0.1
  langfuse_enable: true
  langfuse_host: https://cloud.langfuse.com
  logging_level: DEBUG
  port: 5556
  query_cache_maxsize: 1000
  query_cache_ttl: 3600
  table_column_retrieval_size: 100
  table_retrieval_size: 10
