import { DataSource } from '@/types/dataSource';
import { ModelSyncResponse } from '@/types/project';
import {
  ResolveSchemaChangeWhereInput,
  SchemaChange,
} from '@/types/schemaChange';
import type {
  CreateModelInput,
  RelationInput,
  UpdateCalculatedFieldInput,
  UpdateModelInput,
  UpdateModelMetadataInput,
  UpdateRelationInput,
  UpdateViewMetadataInput,
} from '@/types/modeling';
import {
  buildRuntimeScopeUrl,
  resolveClientRuntimeScopeSelector,
  type ClientRuntimeScopeSelector,
} from '@/runtime/client/runtimeScope';
import type {
  AutoGeneratedRelationsResponse,
  ConnectionTablesResult,
} from '@/types/dataSource';
import type {
  CalculatedFieldValidationResponsePayload,
  CreateCalculatedFieldInput,
} from '@/types/calculatedField';
import { parseRestJsonResponse } from './rest';

export type DeployResponsePayload = {
  status?: string | null;
  error?: string | null;
  version?: string | null;
  hash?: string | null;
  selector?: ClientRuntimeScopeSelector | null;
};

export const buildDeployUrl = (
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl('/api/v1/deploy', {}, selector);

export const buildDeployStatusUrl = (
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl('/api/v1/deploy/status', {}, selector);

export const buildKnowledgeConnectionSaveUrl = (
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl('/api/v1/settings/connection', {}, selector);

export const buildConnectionTablesUrl = (
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl('/api/v1/connection/tables', {}, selector);

export const buildSaveTablesUrl = (
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl('/api/v1/setup/models', {}, selector);

export const buildAutoGeneratedRelationsUrl = (
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl('/api/v1/relationships/auto-generated', {}, selector);

export const buildSaveRelationsUrl = (
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl('/api/v1/relationships/import', {}, selector);

export const buildSchemaChangesUrl = (
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl('/api/v1/schema-changes', {}, selector);

export const buildSchemaChangesDetectUrl = (
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl('/api/v1/schema-changes/detect', {}, selector);

export const buildSchemaChangesResolveUrl = (
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl('/api/v1/schema-changes/resolve', {}, selector);

export const buildModelsCollectionUrl = (
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl('/api/v1/models', {}, selector);

export const buildModelItemUrl = (
  modelId: number,
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl(`/api/v1/models/${modelId}`, {}, selector);

export const buildModelMetadataUrl = (
  modelId: number,
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl(`/api/v1/models/${modelId}/metadata`, {}, selector);

export const buildViewMetadataUrl = (
  viewId: number,
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl(`/api/v1/views/${viewId}/metadata`, {}, selector);

export const buildRelationshipsCollectionUrl = (
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl('/api/v1/relationships', {}, selector);

export const buildRelationshipItemUrl = (
  relationId: number,
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl(`/api/v1/relationships/${relationId}`, {}, selector);

export const buildCalculatedFieldsCollectionUrl = (
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl('/api/v1/calculated-fields', {}, selector);

export const buildCalculatedFieldItemUrl = (
  columnId: number,
  selector = resolveClientRuntimeScopeSelector(),
) =>
  buildRuntimeScopeUrl(`/api/v1/calculated-fields/${columnId}`, {}, selector);

export const buildCalculatedFieldValidateUrl = (
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl('/api/v1/calculated-fields/validate', {}, selector);

export const buildModelSubstituteUrl = (
  selector = resolveClientRuntimeScopeSelector(),
) => buildRuntimeScopeUrl('/api/v1/sql/model-substitute', {}, selector);

export const fetchDeployStatus = async (
  selector: ClientRuntimeScopeSelector,
  options: { signal?: AbortSignal } = {},
) => {
  const response = await fetch(buildDeployStatusUrl(selector), {
    cache: 'no-store',
    signal: options.signal,
  });
  return parseRestJsonResponse<ModelSyncResponse>(
    response,
    '加载部署状态失败，请稍后重试。',
  );
};

export const deployCurrentRuntime = async (
  selector: ClientRuntimeScopeSelector,
) => {
  const response = await fetch(buildDeployUrl(selector), {
    method: 'POST',
  });
  return parseRestJsonResponse<DeployResponsePayload>(
    response,
    '部署失败，请稍后重试。',
  );
};

export const saveKnowledgeConnection = async (
  selector: ClientRuntimeScopeSelector,
  data: {
    type?: DataSource['type'];
    properties: Record<string, any>;
  },
) => {
  const response = await fetch(buildKnowledgeConnectionSaveUrl(selector), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  return parseRestJsonResponse<DataSource>(
    response,
    '保存知识库连接失败，请稍后重试。',
  );
};

export const listConnectionTables = async (
  selector: ClientRuntimeScopeSelector,
) => {
  const response = await fetch(buildConnectionTablesUrl(selector), {
    cache: 'no-store',
  });
  return parseRestJsonResponse<ConnectionTablesResult>(
    response,
    '加载连接资产失败，请稍后重试。',
  );
};

export const saveSetupTables = async (
  selector: ClientRuntimeScopeSelector,
  tables: string[],
) => {
  const response = await fetch(buildSaveTablesUrl(selector), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ tables }),
  });
  return parseRestJsonResponse<any>(response, '保存模型失败，请稍后重试。');
};

export const fetchAutoGeneratedRelations = async (
  selector: ClientRuntimeScopeSelector,
) => {
  const response = await fetch(buildAutoGeneratedRelationsUrl(selector), {
    cache: 'no-store',
  });
  return parseRestJsonResponse<
    AutoGeneratedRelationsResponse['autoGenerateRelation']
  >(response, '加载推荐关系失败，请稍后重试。');
};

export const saveSetupRelations = async (
  selector: ClientRuntimeScopeSelector,
  relations: RelationInput[],
) => {
  const response = await fetch(buildSaveRelationsUrl(selector), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ relations }),
  });
  return parseRestJsonResponse<any>(response, '保存关联关系失败，请稍后重试。');
};

export const fetchSchemaChanges = async (
  selector: ClientRuntimeScopeSelector,
) => {
  const response = await fetch(buildSchemaChangesUrl(selector), {
    cache: 'no-store',
  });
  return parseRestJsonResponse<SchemaChange>(
    response,
    '加载结构变更失败，请稍后重试。',
  );
};

export const triggerSchemaChangeDetection = async (
  selector: ClientRuntimeScopeSelector,
) => {
  const response = await fetch(buildSchemaChangesDetectUrl(selector), {
    method: 'POST',
  });
  return parseRestJsonResponse<boolean>(
    response,
    '检测结构变更失败，请稍后重试。',
  );
};

export const resolveSchemaChange = async (
  selector: ClientRuntimeScopeSelector,
  where: ResolveSchemaChangeWhereInput,
) => {
  const response = await fetch(buildSchemaChangesResolveUrl(selector), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(where),
  });
  return parseRestJsonResponse<{ success: boolean }>(
    response,
    '修复结构变更失败，请稍后重试。',
  );
};

export const createModel = async (
  selector: ClientRuntimeScopeSelector,
  data: CreateModelInput,
) => {
  const response = await fetch(buildModelsCollectionUrl(selector), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  return parseRestJsonResponse<any>(response, '创建模型失败，请稍后重试。');
};

export const updateModel = async (
  selector: ClientRuntimeScopeSelector,
  modelId: number,
  data: UpdateModelInput,
) => {
  const response = await fetch(buildModelItemUrl(modelId, selector), {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  return parseRestJsonResponse<any>(response, '更新模型失败，请稍后重试。');
};

export const deleteModel = async (
  selector: ClientRuntimeScopeSelector,
  modelId: number,
) => {
  const response = await fetch(buildModelItemUrl(modelId, selector), {
    method: 'DELETE',
  });
  return parseRestJsonResponse<{ success: boolean }>(
    response,
    '删除模型失败，请稍后重试。',
  );
};

export const updateModelMetadata = async (
  selector: ClientRuntimeScopeSelector,
  modelId: number,
  data: UpdateModelMetadataInput,
) => {
  const response = await fetch(buildModelMetadataUrl(modelId, selector), {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  return parseRestJsonResponse<{ success: boolean }>(
    response,
    '更新模型元数据失败，请稍后重试。',
  );
};

export const updateViewMetadata = async (
  selector: ClientRuntimeScopeSelector,
  viewId: number,
  data: UpdateViewMetadataInput,
) => {
  const response = await fetch(buildViewMetadataUrl(viewId, selector), {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  return parseRestJsonResponse<{ success: boolean }>(
    response,
    '更新视图元数据失败，请稍后重试。',
  );
};

export const createRelationship = async (
  selector: ClientRuntimeScopeSelector,
  data: RelationInput,
) => {
  const response = await fetch(buildRelationshipsCollectionUrl(selector), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  return parseRestJsonResponse<any>(response, '创建关系失败，请稍后重试。');
};

export const updateRelationship = async (
  selector: ClientRuntimeScopeSelector,
  relationId: number,
  data: UpdateRelationInput,
) => {
  const response = await fetch(buildRelationshipItemUrl(relationId, selector), {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  return parseRestJsonResponse<any>(response, '更新关系失败，请稍后重试。');
};

export const deleteRelationship = async (
  selector: ClientRuntimeScopeSelector,
  relationId: number,
) => {
  const response = await fetch(buildRelationshipItemUrl(relationId, selector), {
    method: 'DELETE',
  });
  return parseRestJsonResponse<{ success: boolean }>(
    response,
    '删除关系失败，请稍后重试。',
  );
};

export const validateCalculatedField = async (
  selector: ClientRuntimeScopeSelector,
  data: {
    name: string;
    modelId: number;
    columnId?: number;
  },
) => {
  const response = await fetch(buildCalculatedFieldValidateUrl(selector), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  return parseRestJsonResponse<
    CalculatedFieldValidationResponsePayload['validateCalculatedField']
  >(response, '校验计算字段失败，请稍后重试。');
};

export const createCalculatedField = async (
  selector: ClientRuntimeScopeSelector,
  data: CreateCalculatedFieldInput,
) => {
  const response = await fetch(buildCalculatedFieldsCollectionUrl(selector), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  return parseRestJsonResponse<any>(response, '创建计算字段失败，请稍后重试。');
};

export const updateCalculatedField = async (
  selector: ClientRuntimeScopeSelector,
  columnId: number,
  data: UpdateCalculatedFieldInput,
) => {
  const response = await fetch(
    buildCalculatedFieldItemUrl(columnId, selector),
    {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    },
  );
  return parseRestJsonResponse<any>(response, '更新计算字段失败，请稍后重试。');
};

export const deleteCalculatedField = async (
  selector: ClientRuntimeScopeSelector,
  columnId: number,
) => {
  const response = await fetch(
    buildCalculatedFieldItemUrl(columnId, selector),
    {
      method: 'DELETE',
    },
  );
  return parseRestJsonResponse<{ success: boolean }>(
    response,
    '删除计算字段失败，请稍后重试。',
  );
};

export const substituteDialectSql = async (
  selector: ClientRuntimeScopeSelector,
  sql: string,
) => {
  const response = await fetch(buildModelSubstituteUrl(selector), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ sql }),
  });
  return parseRestJsonResponse<string>(response, 'SQL 转换失败，请稍后重试。');
};
