# golangci-lint configuration for WrenAI wren-launcher
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck      # 檢查未處理的錯誤 (enabled by default)
    - govet         # 檢查可疑的構造 (enabled by default)
    - ineffassign   # 檢查未使用的賦值 (enabled by default)
    - staticcheck   # 靜態分析檢查 (enabled by default)
    - unused        # 檢查未使用的常量、變量、函數和類型 (enabled by default)
    - misspell      # 找出拼寫錯誤的英文單詞
    - unconvert     # 移除不必要的類型轉換
    - gosec         # 檢查安全問題
    - dupl          # 檢測重複代碼
    - goconst       # 找出可替換為常量的重複字符串
    - gocyclo       # 檢查函數的圈複雜度
    - bodyclose     # 檢查 HTTP response body 是否正確關閉
    - whitespace    # 檢查不必要的空行
    - gocheckcompilerdirectives  # 檢查編譯器指令註釋

linters-settings:
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
  exclude-rules:
    # 在測試文件中放寬一些檢查
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
