import { useMemo, useState } from 'react';
import { JOIN_TYPE, NODE_TYPE } from '@/utils/enum';
import {
  ComposeDiagram,
  Diagram,
  DiagramModelRelationField,
} from '@/utils/data';
import useModalAction from '@/hooks/useModalAction';
import { SelectedRecommendRelations } from '@/components/pages/setup/DefineRelations';

type RelationshipModalData = ComposeDiagram | DiagramModelRelationField;

const isRelationNode = (
  value: RelationshipModalData,
): value is DiagramModelRelationField => value.nodeType === NODE_TYPE.RELATION;

export default function useRelationshipModal(diagramData: Diagram | null) {
  const relationshipModal = useModalAction();

  const [selectedModelReferenceName, setSelectedModelReferenceName] = useState<
    string | null
  >(null);

  // Parse out the relationships data under all models
  const relationships = useMemo<SelectedRecommendRelations>(
    () =>
      (diagramData?.models || []).reduce((acc, currentValue) => {
        if (!currentValue) {
          return acc;
        }
        const { referenceName, relationFields } = currentValue;
        const newRelationship = (relationFields || [])
          .filter((relationship): relationship is DiagramModelRelationField =>
            Boolean(relationship),
          )
          .map((relationship) => {
            return {
              name: relationship.displayName || relationship.referenceName,
              fromField: {
                modelId: String(relationship.fromModelId),
                modelName: relationship.fromModelName,
                fieldId: String(relationship.fromColumnId),
                fieldName: relationship.fromColumnName,
              },
              toField: {
                modelId: String(relationship.toModelId),
                modelName: relationship.toModelName,
                fieldId: String(relationship.toColumnId),
                fieldName: relationship.toColumnName,
              },
              type: relationship.type as JOIN_TYPE,
              isAutoGenerated: false,
              properties: {},
            };
          });

        acc[referenceName] = newRelationship;
        return acc;
      }, {} as SelectedRecommendRelations),
    [diagramData],
  );

  const onClose = () => {
    setSelectedModelReferenceName(null);
    relationshipModal.closeModal();
  };

  const openModal = (data: RelationshipModalData) => {
    // update mode
    if (isRelationNode(data)) {
      setSelectedModelReferenceName(data.fromModelName);
      relationshipModal.openModal({
        relationId: data.relationId,
        fromField: {
          modelId: String(data.fromModelId),
          modelName: data.fromModelName,
          fieldId: String(data.fromColumnId),
          fieldName: data.fromColumnName,
        },
        toField: {
          modelId: String(data.toModelId),
          modelName: data.toModelName,
          fieldId: String(data.toColumnId),
          fieldName: data.toColumnName,
        },
        type: data.type as JOIN_TYPE,
      });
      return;
    }

    // create mode
    setSelectedModelReferenceName(data.referenceName);
    relationshipModal.openModal();
  };

  return {
    onClose,
    openModal,
    state: {
      ...relationshipModal.state,
      model: selectedModelReferenceName || '',
      relations: relationships,
    },
  };
}
