import { useMemo, useState } from 'react';
import { message } from 'antd';
import { SETUP } from '@/utils/enum';
import { SelectedRecommendRelations } from '@/components/pages/setup/DefineRelations';
import { Path } from '@/utils/enum';
import {
  useAutoGeneratedRelationsQuery,
  useSaveRelationsMutation,
} from '@/apollo/client/graphql/dataSource.generated';
import useOnboardingStatus from '@/hooks/useCheckOnboarding';
import useRuntimeScopeNavigation from './useRuntimeScopeNavigation';

export default function useSetupRelations() {
  const [stepKey] = useState(SETUP.DEFINE_RELATIONS);
  const runtimeScopeNavigation = useRuntimeScopeNavigation();
  const { refetch: refetchOnboardingStatus } = useOnboardingStatus();

  const { data, loading: fetching } = useAutoGeneratedRelationsQuery({
    fetchPolicy: 'no-cache',
  });
  const autoGenerateRelation = data?.autoGenerateRelation;

  const onFinish = () => {
    runtimeScopeNavigation.push(Path.Modeling);
    refetchOnboardingStatus();
  };

  const [saveRelationsMutation, { loading: submitting }] =
    useSaveRelationsMutation({
      onError: (error) =>
        message.error(error.message || '保存关联关系失败，请稍后重试'),
      onCompleted: onFinish,
    });

  const submitRelations = async (relationsData: SelectedRecommendRelations) => {
    const relations = Object.entries(relationsData).flatMap(
      ([_modelName, relationItems]) =>
        relationItems.map((relation) => ({
          fromModelId: Number(relation.fromField.modelId),
          fromColumnId: Number(relation.fromField.fieldId),
          toModelId: Number(relation.toField.modelId),
          toColumnId: Number(relation.toField.fieldId),
          type: relation.type,
        })),
    );

    // redirect to the home page if there is no relationship data needs to be saved
    if (relations.length === 0) {
      onFinish();
      return;
    }

    await saveRelationsMutation({
      variables: { data: { relations } },
    });
  };

  const onBack = () => {
    runtimeScopeNavigation.push(Path.OnboardingModels);
  };

  const onNext = (data: { relations: SelectedRecommendRelations }) => {
    submitRelations(data.relations);
  };

  const recommendRelationsResult = useMemo(
    () =>
      (autoGenerateRelation || []).reduce<{
        recommendRelations: SelectedRecommendRelations;
        recommendNameMapping: Record<string, string>;
      }>(
        (acc, currentValue) => {
          const { displayName, referenceName, relations } = currentValue;
          const newRelations = relations
            .filter((relation): relation is NonNullable<typeof relation> =>
              Boolean(relation),
            )
            .map((relation) => ({
              name: relation.name,
              fromField: {
                modelId: String(relation.fromModelId),
                modelName: relation.fromModelReferenceName,
                fieldId: String(relation.fromColumnId),
                fieldName: relation.fromColumnReferenceName,
              },
              toField: {
                modelId: String(relation.toModelId),
                modelName: relation.toModelReferenceName,
                fieldId: String(relation.toColumnId),
                fieldName: relation.toColumnReferenceName,
              },
              type: relation.type,
              isAutoGenerated: true,
              properties: {},
            }));

          acc.recommendRelations[referenceName] = newRelations;
          acc.recommendNameMapping[referenceName] = displayName;
          return acc;
        },
        {
          recommendRelations: {},
          recommendNameMapping: {},
        },
      ),
    [autoGenerateRelation],
  );

  return {
    fetching,
    submitting,
    stepKey,
    recommendRelationsResult,
    onBack,
    onNext,
    onSkip: onFinish,
  };
}
