volumes:
  data:
  postgres_data:

networks:
  wren:
    driver: bridge

services:
  bootstrap:
    image: ghcr.io/canner/wren-bootstrap:${WREN_BOOTSTRAP_VERSION}
    restart: on-failure
    platform: ${PLATFORM}
    environment:
      DATA_PATH: /app/data
    volumes:
      - data:/app/data
    command: /bin/sh /app/init.sh

  wren-engine:
    image: ${WREN_ENGINE_IMAGE_REPO:-wren-engine}:${WREN_ENGINE_IMAGE_TAG:-local}
    build:
      context: ../wren-engine
      dockerfile: docker/wren-engine.Dockerfile
    restart: on-failure
    platform: ${PLATFORM}
    expose:
      - ${WREN_ENGINE_PORT}
      - ${WREN_ENGINE_SQL_PORT}
    ports:
      - ${WREN_ENGINE_PORT}:${WREN_ENGINE_PORT}
      - ${WREN_ENGINE_SQL_PORT}:${WREN_ENGINE_SQL_PORT}
    volumes:
      - data:/usr/src/app/etc
      - ${PROJECT_DIR}/data:/usr/src/app/data
    networks:
      - wren
    depends_on:
      - bootstrap

  ibis-server:
    image: ${IBIS_SERVER_IMAGE_REPO:-wren-engine-ibis}:${IBIS_SERVER_IMAGE_TAG:-local}
    build:
      context: ../wren-engine
      dockerfile: docker/ibis-server.Dockerfile
      args:
        ENV: ${IBIS_SERVER_BUILD_ENV:-prod}
    restart: on-failure
    platform: ${PLATFORM}
    expose:
      - ${IBIS_SERVER_PORT}
    ports:
      - ${IBIS_SERVER_PORT}:${IBIS_SERVER_PORT}
    environment:
      WREN_ENGINE_ENDPOINT: http://wren-engine:${WREN_ENGINE_PORT}
    volumes:
      - ${LOCAL_STORAGE:-.}:/usr/src/app/data
    networks:
      - wren

  trino:
    image: trinodb/trino:${TRINO_VERSION:-475}
    restart: on-failure
    platform: ${PLATFORM}
    environment:
      CATALOG_MANAGEMENT: ${TRINO_CATALOG_MANAGEMENT:-dynamic}
    expose:
      - 8080
    ports:
      - ${TRINO_FORWARD_PORT:-8081}:8080
    volumes:
      - ${PROJECT_DIR}/.trino/catalog:/etc/trino/catalog
    networks:
      - wren

  wren-ai-service:
    image: ghcr.io/canner/wren-ai-service:${WREN_AI_SERVICE_VERSION}
    restart: on-failure
    platform: ${PLATFORM}
    expose:
      - ${WREN_AI_SERVICE_PORT}
    ports:
      - ${AI_SERVICE_FORWARD_PORT}:${WREN_AI_SERVICE_PORT}
    env_file:
      - ${PROJECT_DIR}/.env
    environment:
      # sometimes the console won't show print messages,
      # using PYTHONUNBUFFERED: 1 can fix this
      PYTHONUNBUFFERED: 1
      CONFIG_PATH: /app/config.yaml
      PG_CONN_STR: ${PG_CONN_STR:-postgresql://postgres:postgres@postgres:5432/wrenai}
      EMBEDDING_MODEL_DIMENSION: ${EMBEDDING_MODEL_DIMENSION:-3072}
    volumes:
      - ${PROJECT_DIR}/config.yaml:/app/config.yaml:ro
      - ${PROJECT_DIR}/data:/app/data:ro
    networks:
      - wren
    depends_on:
      - postgres

  postgres:
    image: pgvector/pgvector:pg17
    restart: on-failure
    expose:
      - 5432
    ports:
      - ${POSTGRES_FORWARD_PORT:-9432}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-wrenai}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    networks:
      - wren

  wren-ui:
    image: ghcr.io/canner/wren-ui:${WREN_UI_VERSION}
    restart: on-failure
    platform: ${PLATFORM}
    environment:
      PG_URL: ${PG_URL:-postgres://postgres:postgres@postgres:5432/wrenai}
      WREN_ENGINE_ENDPOINT: http://wren-engine:${WREN_ENGINE_PORT}
      WREN_AI_ENDPOINT: http://wren-ai-service:${WREN_AI_SERVICE_PORT}
      IBIS_SERVER_ENDPOINT: http://ibis-server:${IBIS_SERVER_PORT}
      TRINO_CATALOG_DIR: /app/.trino/catalog
      TRINO_CATALOG_MANAGEMENT: ${TRINO_CATALOG_MANAGEMENT:-dynamic}
      TRINO_CATALOG_MANAGEMENT_HOST: trino
      TRINO_CATALOG_MANAGEMENT_PORT: 8080
      TRINO_CATALOG_MANAGEMENT_SSL: false
      TRINO_RUNTIME_HOST: trino
      TRINO_RUNTIME_PORT: 8080
      TRINO_RUNTIME_USER: ${TRINO_RUNTIME_USER:-wrenai}
      TRINO_RUNTIME_PASSWORD: ${TRINO_RUNTIME_PASSWORD:-}
      TRINO_RUNTIME_SSL: ${TRINO_RUNTIME_SSL:-false}
      # this is for telemetry to know the model, i think ai-service might be able to provide a endpoint to get the information
      GENERATION_MODEL: ${GENERATION_MODEL}
      # telemetry
      WREN_ENGINE_PORT: ${WREN_ENGINE_PORT}
      WREN_AI_SERVICE_VERSION: ${WREN_AI_SERVICE_VERSION}
      WREN_UI_VERSION: ${WREN_UI_VERSION}
      WREN_ENGINE_VERSION: ${WREN_ENGINE_VERSION}
      USER_UUID: ${USER_UUID}
      POSTHOG_API_KEY: ${POSTHOG_API_KEY}
      POSTHOG_HOST: ${POSTHOG_HOST}
      TELEMETRY_ENABLED: ${TELEMETRY_ENABLED}
      # client side
      NEXT_PUBLIC_USER_UUID: ${USER_UUID}
      NEXT_PUBLIC_POSTHOG_API_KEY: ${POSTHOG_API_KEY}
      NEXT_PUBLIC_POSTHOG_HOST: ${POSTHOG_HOST}
      NEXT_PUBLIC_TELEMETRY_ENABLED: ${TELEMETRY_ENABLED}
      EXPERIMENTAL_ENGINE_RUST_VERSION: ${EXPERIMENTAL_ENGINE_RUST_VERSION}
      # configs
      WREN_PRODUCT_VERSION: ${WREN_PRODUCT_VERSION}
    ports:
      # HOST_PORT is the port you want to expose to the host machine
      - ${HOST_PORT}:3000
    volumes:
      - data:/app/data
      - ${PROJECT_DIR}/.trino/catalog:/app/.trino/catalog
    networks:
      - wren
    depends_on:
      - wren-ai-service
      - wren-engine
      - postgres
      - trino
