import type {
  KnowledgeInstructionStageArgs,
  KnowledgeInstructionsStageProps,
  KnowledgeSqlStageArgs,
  KnowledgeSqlTemplatesStageProps,
} from './knowledgeMainStageEditorSectionPropTypes';

export function buildKnowledgeSqlTemplatesStageProps({
  createSqlPairLoading,
  editingSqlPair,
  editors,
  isKnowledgeMutationDisabled,
  sqlList,
  sqlManageLoading,
  sqlTemplateForm,
  updateSqlPairLoading,
}: KnowledgeSqlStageArgs): KnowledgeSqlTemplatesStageProps {
  return {
    applySqlContextDraft: editors.applySqlContextDraft,
    createSqlPairLoading,
    editingSqlPair,
    handleCloseSqlTemplateDrawer: editors.handleCloseSqlTemplateDrawer,
    handleCreateRuleFromAsset: editors.handleCreateRuleFromAsset,
    handleDeleteSqlTemplate: editors.handleDeleteSqlTemplate,
    handleDuplicateSqlTemplate: editors.handleDuplicateSqlTemplate,
    handleResetSqlTemplateEditor: editors.handleResetSqlTemplateEditor,
    handleSubmitSqlTemplateDetail: editors.handleSubmitSqlTemplateDetail,
    isKnowledgeMutationDisabled,
    openSqlTemplateEditor: editors.openSqlTemplateEditor,
    setSqlContextAssetId: editors.setSqlContextAssetId,
    setSqlListMode: editors.setSqlListMode,
    setSqlSearchKeyword: editors.setSqlSearchKeyword,
    sqlContextAsset: editors.sqlContextAsset,
    sqlContextAssetId: editors.sqlContextAssetId,
    sqlList,
    sqlListMode: editors.sqlListMode,
    sqlManageLoading,
    sqlSearchKeyword: editors.sqlSearchKeyword,
    sqlTemplateAssetOptions: editors.sqlTemplateAssetOptions,
    sqlTemplateDrawerOpen: editors.sqlTemplateDrawerOpen,
    sqlTemplateForm,
    updateSqlPairLoading,
    visibleSqlList: editors.visibleSqlList,
  };
}

export function buildKnowledgeInstructionsStageProps({
  createInstructionLoading,
  editingInstruction,
  editors,
  isKnowledgeMutationDisabled,
  ruleForm,
  ruleList,
  ruleManageLoading,
  updateInstructionLoading,
}: KnowledgeInstructionStageArgs): KnowledgeInstructionsStageProps {
  return {
    applyRuleContextDraft: editors.applyRuleContextDraft,
    assetOptions: editors.sqlTemplateAssetOptions,
    createInstructionLoading,
    editingInstruction,
    handleCloseRuleDrawer: editors.handleCloseRuleDrawer,
    handleCreateSqlTemplateFromAsset: editors.handleCreateSqlTemplateFromAsset,
    handleDeleteRule: editors.handleDeleteRule,
    handleDuplicateRule: editors.handleDuplicateRule,
    handleResetRuleDetailEditor: editors.handleResetRuleDetailEditor,
    handleSubmitRuleDetail: editors.handleSubmitRuleDetail,
    isKnowledgeMutationDisabled,
    openRuleEditor: editors.openRuleEditor,
    ruleContextAsset: editors.ruleContextAsset,
    ruleContextAssetId: editors.ruleContextAssetId,
    ruleDrawerOpen: editors.ruleDrawerOpen,
    ruleForm,
    ruleList,
    ruleListScope: editors.ruleListScope,
    ruleManageLoading,
    ruleSearchKeyword: editors.ruleSearchKeyword,
    setRuleContextAssetId: editors.setRuleContextAssetId,
    setRuleListScope: editors.setRuleListScope,
    setRuleSearchKeyword: editors.setRuleSearchKeyword,
    updateInstructionLoading,
    visibleRuleList: editors.visibleRuleList,
  };
}
