use std::sync::Arc;

use datafusion::{
    config::ConfigOptions,
    functions::{
        core::{coalesce, greatest, least, named_struct, nullif, nvl, nvl2},
        crypto::{md5, sha256, sha512},
        datetime::{current_date, current_time, date_trunc, from_unixtime, now},
        math::{
            abs, acos, acosh, asin, asinh, atan, atan2, atanh, cbrt, ceil, cos, cosh,
            cot, floor, ln, log, log10, log2, power, random, round, signum, sin, sinh,
            sqrt, tan, tanh, trunc,
        },
        regex::{regexp_instr, regexp_like, regexp_replace},
        string::{
            concat, contains, lower, ltrim, octet_length, repeat, replace, rtrim,
            starts_with, to_hex, upper, uuid,
        },
        unicode::{
            left, lpad, reverse, right, rpad, strpos, substr, substring, translate,
        },
    },
    functions_aggregate::{
        approx_distinct::approx_distinct_udaf,
        array_agg::array_agg_udaf,
        average::avg_udaf,
        bit_and_or_xor::{bit_and_udaf, bit_or_udaf, bit_xor_udaf},
        bool_and_or::{bool_and_udaf, bool_or_udaf},
        correlation::corr_udaf,
        count::count_udaf,
        covariance::{covar_pop_udaf, covar_samp_udaf},
        grouping::grouping_udaf,
        min_max::{max_udaf, min_udaf},
        stddev::{stddev_pop_udaf, stddev_udaf},
        string_agg::string_agg_udaf,
        sum::sum_udaf,
        variance::{var_pop_udaf, var_samp_udaf},
    },
    functions_nested::{
        array_has::array_has_udf,
        cardinality::cardinality_udf,
        concat::array_concat_udf,
        extract::{array_element_udf, array_slice_udf},
        length::array_length_udf,
        make_array::make_array_udf,
        range::range_udf,
        reverse::array_reverse_udf,
        string::array_to_string_udf,
    },
    functions_window::{
        cume_dist::cume_dist_udwf,
        lead_lag::{lag_udwf, lead_udwf},
        nth_value::{first_value_udwf, last_value_udwf, nth_value_udwf},
        ntile::ntile_udwf,
        rank::{dense_rank_udwf, percent_rank_udwf, rank_udwf},
        row_number::row_number_udwf,
    },
    logical_expr::{AggregateUDF, ScalarUDF, WindowUDF},
};

use aggregate::*;
use scalar::*;
use window::*;

use crate::mdl::function::scalar::json;
use crate::mdl::function::scalar::to_char;
mod aggregate;
mod scalar;
mod window;

/// https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-all#function_list
pub fn bigquery_scalar_functions() -> Vec<Arc<ScalarUDF>> {
    let config = ConfigOptions::default();
    vec![
        // array() isn't supported by Wren
        // list_cat, list_concat
        array_concat_udf(),
        array_first(),
        array_last(),
        array_reverse_udf(),
        array_slice_udf(),
        array_to_string_udf(),
        array_length_udf(),
        generate_array(),
        generate_date_array(),
        generate_timestamp_array(),
        bit_count(),
        parse_bignumeric(),
        parse_numeric(),
        current_date(),
        date(),
        date_add(),
        date_diff(),
        date_from_unix_date(),
        date_sub(),
        date_trunc(),
        format_date(),
        parse_date(),
        unix_date(),
        farm_fingerprint(),
        md5(),
        sha1(),
        sha256(),
        sha512(),
        justify_days(),
        justify_hours(),
        justify_interval(),
        bool(),
        float64(),
        int64(),
        json_array(),
        json_array_append(),
        json_array_insert(),
        json_extract(),
        json_extract_array(),
        json_extract_scalar(),
        json_extract_string_array(),
        json_keys(),
        json_object(),
        json_query(),
        json_query_array(),
        json_remove(),
        json_set(),
        json_remove(),
        json_set(),
        json_strip_nulls(),
        json_type(),
        json_value(),
        json_value_array(),
        lax_bool(),
        lax_float64(),
        lax_int64(),
        lax_string(),
        parse_json(),
        string(),
        to_json(),
        to_json_string(),
        abs(),
        acos(),
        acosh(),
        asin(),
        asinh(),
        atan(),
        atan2(),
        atanh(),
        cbrt(),
        ceil(),
        ceiling(),
        cos(),
        cosh(),
        cosine_distance(),
        cot(),
        coth(),
        csc(),
        csch(),
        div(),
        exp(),
        euclidean_distance(),
        floor(),
        greatest(),
        is_inf(),
        is_nan(),
        least(),
        ln(),
        log(),
        log10(),
        r#mod(),
        power(),
        rand(),
        safe_add(),
        safe_divide(),
        safe_multiply(),
        safe_subtract(),
        safe_negate(),
        sec(),
        sech(),
        sign(),
        sin(),
        sinh(),
        sqrt(),
        tan(),
        tanh(),
        trunc(),
        generate_range_array(),
        range_udf(),
        range_contains(),
        range_end(),
        range_intersect(),
        range_overlaps(),
        range_start(),
        ascii(),
        byte_length(),
        char_length(),
        character_length(),
        chr(),
        code_points_to_bytes(),
        code_points_to_string(),
        collate(),
        concat(),
        contains_substr(),
        edit_distance(),
        ends_with(),
        format(),
        from_base32(),
        from_base64(),
        from_hex(),
        initcap(),
        left(),
        length(),
        lower(),
        lpad(),
        ltrim(),
        normalize(),
        normalize_and_casefold(),
        octet_length(),
        regexp_contains(),
        regexp_extract(),
        regexp_extract_all(),
        regexp_instr(),
        regexp_replace(),
        regexp_substr(),
        repeat(),
        replace(),
        reverse(),
        right(),
        rpad(),
        rtrim(),
        safe_convert_bytes_to_string(),
        soundex(),
        split(),
        starts_with(),
        // instr, position
        strpos(),
        substr(),
        substring(),
        to_base32(),
        to_base64(),
        to_hex(),
        to_code_points(),
        translate(),
        trim(),
        unicode(),
        upper(),
        current_time(),
        format_time(),
        parse_time(),
        time(),
        time_add(),
        time_diff(),
        time_sub(),
        time_trunc(),
        format_timestamp(),
        parse_timestamp(),
        timestamp(),
        timestamp_add(),
        timestamp_diff(),
        timestamp_micros(),
        timestamp_millis(),
        timestamp_seconds(),
        timestamp_sub(),
        timestamp_trunc(),
        unix_micros(),
        unix_millis(),
        unix_seconds(),
        current_datetime(),
        datetime(),
        datetime_add(),
        datetime_diff(),
        datetime_sub(),
        datetime_trunc(),
        format_datetime(),
        parse_datetime(),
        round(),
        nvl(),
        nullif(),
        array_has_udf(),
        cardinality_udf(),
        signum(),
        contains(),
        array_element_udf(),
        now(&config),
        uuid(),
        from_unixtime(),
        make_array_udf(),
        to_char(),
        power(),
        regexp_like(),
        nvl2(),
        named_struct(),
        random(),
        coalesce(),
        log2(),
        offset(),
        ordinal(),
        safe_offset(),
        safe_ordinal(),
        json::get_path(),
        json::as_array(),
        json::as_varchar(),
        json::as_integer(),
        json::as_double(),
        json::as_boolean(),
    ]
}

pub fn bigquery_aggregate_functions() -> Vec<Arc<AggregateUDF>> {
    vec![
        any_value(),
        approx_count_distinct(),
        approx_quantiles(),
        approx_top_count(),
        approx_top_sum(),
        approx_distinct_udaf(),
        array_agg_udaf(),
        array_concat_agg(),
        avg_udaf(),
        bit_and_udaf(),
        bit_or_udaf(),
        bit_xor_udaf(),
        count_udaf(),
        countif(),
        grouping_udaf(),
        logical_and(),
        logical_or(),
        max_udaf(),
        max_by(),
        min_udaf(),
        min_by(),
        string_agg_udaf(),
        sum_udaf(),
        corr_udaf(),
        covar_pop_udaf(),
        covar_samp_udaf(),
        stddev_udaf(),
        stddev_pop_udaf(),
        stddev_samp(),
        var_pop_udaf(),
        var_samp_udaf(),
        variance(),
        bool_or_udaf(),
        bool_and_udaf(),
        group_concat(),
    ]
}

pub fn bigquery_window_functions() -> Vec<Arc<WindowUDF>> {
    vec![
        first_value_udwf(),
        lag_udwf(),
        last_value_udwf(),
        lead_udwf(),
        nth_value_udwf(),
        percentile_cont_udwf(),
        percentile_disc_udwf(),
        cume_dist_udwf(),
        dense_rank_udwf(),
        ntile_udwf(),
        percent_rank_udwf(),
        rank_udwf(),
        row_number_udwf(),
    ]
}
