-- 表5.4 理财产品业务表
-- Wealth Product Business Table
CREATE TABLE wealth_product_business (
    -- 监管字段 (Regulatory Fields)
    product_id VARCHAR(32) NOT NULL COMMENT 'E040001-产品ID',
    institution_id VARCHAR(24) NOT NULL COMMENT 'E040002-机构ID',
    product_code VARCHAR(255) COMMENT 'E040003-产品编号',
    wealth_product_code VARCHAR(255) COMMENT 'E040004-理财产品代码',
    product_name TEXT COMMENT 'E040005-产品名称',
    issuer_institution_code VARCHAR(6) COMMENT 'E040006-发行机构代码',
    issuer_institution_name TEXT COMMENT 'E040007-发行机构名称',
    wealth_issuer_institution_type VARCHAR(2) COMMENT 'E040008-理财发行机构类型',
    product_special_attribute VARCHAR(20) COMMENT 'E040009-产品特殊属性',
    product_period TEXT COMMENT 'E040010-产品期次',
    product_risk_level VARCHAR(2) COMMENT 'E040011-产品风险等级',
    target_customer_type VARCHAR(2) COMMENT 'E040012-目标客户类型',
    fund_investment_region VARCHAR(2) COMMENT 'E040013-资金投向地区',
    product_operation_mode VARCHAR(2) COMMENT 'E040014-产品运作模式',
    product_asset_allocation_method VARCHAR(2) COMMENT 'E040015-产品资产配置方式',
    product_management_mode VARCHAR(2) COMMENT 'E040016-产品管理模式',
    actual_manager TEXT COMMENT 'E040017-实际管理人',
    management_method VARCHAR(2) COMMENT 'E040018-管理方式',
    product_approval_employee_id VARCHAR(100) COMMENT 'E040019-产品审批员工ID',
    investment_manager_id_number VARCHAR(100) COMMENT 'E040020-投资经理身份证号',
    investment_manager_name VARCHAR(200) COMMENT 'E040021-投资经理姓名',
    product_pricing_method VARCHAR(2) COMMENT 'E040022-产品定价方式',
    structured_product_underlying TEXT COMMENT 'E040023-结构性产品挂钩标的',
    cooperation_mode VARCHAR(2) COMMENT 'E040024-合作模式',
    cooperation_institution_name TEXT COMMENT 'E040025-合作机构名称',
    investment_asset_type_ratio TEXT COMMENT 'E040026-投资资产种类及比例',
    fundraising_currency VARCHAR(700) COMMENT 'E040027-募集币种',
    principal_payment_currency VARCHAR(700) COMMENT 'E040028-兑付本金币种',
    income_payment_currency VARCHAR(700) COMMENT 'E040029-兑付收益币种',
    investment_principal_arrival_date VARCHAR(2) COMMENT 'E040030-投资本金到账日',
    investment_income_arrival_date VARCHAR(2) COMMENT 'E040031-投资收益到账日',
    issuer_early_termination_flag TINYINT(1) COMMENT 'E040032-发行机构提前终止权标识',
    customer_redemption_flag TINYINT(1) COMMENT 'E040033-客户赎回权标识',
    product_enhancement_flag TINYINT(1) COMMENT 'E040034-产品增信标识',
    product_enhancement_form VARCHAR(2) COMMENT 'E040035-产品增信形式',
    structured_hierarchical_product_flag TINYINT(1) COMMENT 'E040036-结构化（分级）产品标识',
    hierarchy_category VARCHAR(2) COMMENT 'E040037-层级类别',
    yield_tier_description TEXT COMMENT 'E040038-收益率分档说明',
    open_mode VARCHAR(2) COMMENT 'E040039-开放模式',
    regular_open_cycle VARCHAR(2) COMMENT 'E040040-规律开放周期',
    other_regular_open_cycle INT COMMENT 'E040041-其他规律开放周期',
    holiday_open_flag TINYINT(1) COMMENT 'E040042-节假日开放标识',
    average_open_frequency DECIMAL(8,2) COMMENT 'E040043-平均开放次数',
    open_period_business_type VARCHAR(2) COMMENT 'E040044-开放期业务类型',
    fundraising_start_date DATE COMMENT 'E040045-募集起始日期',
    fundraising_end_date DATE COMMENT 'E040046-募集结束日期',
    product_actual_termination_date DATE COMMENT 'E040047-产品实际终止日期',
    report_registration_date DATE COMMENT 'E040048-报告登记日期',
    termination_registration_date DATE COMMENT 'E040049-终止登记日期',
    issue_registration_date DATE COMMENT 'E040050-发行登记日期',
    fundraising_registration_date DATE COMMENT 'E040051-募集登记日期',
    wealth_product_term VARCHAR(2) COMMENT 'E040083-理财产品期限',
    wealth_product_status VARCHAR(2) COMMENT 'E040052-理财产品状态',
    product_sales_region VARCHAR(2) COMMENT 'E040053-产品销售区域',
    other_institution_sales_flag TINYINT(1) COMMENT 'E040054-其他机构代销标识',
    domestic_custodian_institution_code VARCHAR(255) COMMENT 'E040055-境内托管机构代码',
    domestic_custodian_institution_name TEXT COMMENT 'E040056-境内托管机构名称',
    overseas_custodian_institution_country VARCHAR(128) COMMENT 'E040057-境外托管机构国家地区',
    overseas_custodian_institution_name TEXT COMMENT 'E040058-境外托管机构名称',
    wealth_product_fund_custody_account VARCHAR(255) COMMENT 'E040059-理财产品资金托管账号',
    wealth_product_fund_custody_account_name TEXT COMMENT 'E040060-理财产品资金托管账户名称',
    new_old_product_flag VARCHAR(2) COMMENT 'E040061-新老产品标识',
    product_fundraising_method VARCHAR(2) COMMENT 'E040062-产品募集方式',
    product_investment_nature VARCHAR(2) COMMENT 'E040063-产品投资性质',
    minimum_holding_period_flag TINYINT(1) COMMENT 'E040064-设置最短持有期限标识',
    minimum_holding_period_days INT COMMENT 'E040065-最短持有期限（天）',
    free_redemption_after_minimum_holding_flag TINYINT(1) COMMENT 'E040066-最短持有期后自由赎回标识',
    cash_management_wealth_product_flag TINYINT(1) COMMENT 'E040067-现金管理类理财产品标识',
    performance_benchmark_upper_limit DECIMAL(20,6) COMMENT 'E040068-业绩比较基准上限',
    performance_benchmark_lower_limit DECIMAL(20,6) COMMENT 'E040069-业绩比较基准下限',
    performance_benchmark_description TEXT COMMENT 'E040070-业绩比较基准说明',
    investment_management_fee_rate DECIMAL(20,6) COMMENT 'E040071-投资管理费率',
    financial_industry_exclusive_flag TINYINT(1) COMMENT 'E040072-金融同业专属标识',
    custody_fee_rate DECIMAL(20,6) COMMENT 'E040073-托管费率',
    planned_fundraising_amount DECIMAL(20,2) COMMENT 'E040074-计划募集金额',
    actual_fundraising_amount DECIMAL(20,2) COMMENT 'E040075-实际募集金额',
    bank_actual_realized_income DECIMAL(20,2) COMMENT 'E040076-银行实际实现收入',
    payment_customer_income DECIMAL(20,2) COMMENT 'E040077-兑付客户收益',
    payment_customer_total_amount DECIMAL(20,2) COMMENT 'E040078-兑付客户总金额',
    customer_actual_annual_yield DECIMAL(20,6) COMMENT 'E040079-客户实际年化收益率',
    product_actual_annual_yield DECIMAL(20,6) COMMENT 'E040080-产品实际年化收益率',
    remarks TEXT COMMENT 'E040081-备注',
    collection_date DATE NOT NULL COMMENT 'E040082-采集日期',

    -- 数据治理字段 (Data Governance Fields)
    data_owner_dept VARCHAR(100) NOT NULL COMMENT '数据归属部门',
    data_source_system VARCHAR(100) NOT NULL COMMENT '数据来源系统',

    -- 时间戳字段 (Timestamp Fields)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',

    -- 主键约束
    PRIMARY KEY (product_id, institution_id),

    -- 索引
    INDEX idx_product_code (product_code),
    INDEX idx_wealth_product_code (wealth_product_code),
    INDEX idx_product_name (product_name(255)),
    INDEX idx_issuer_institution_code (issuer_institution_code),
    INDEX idx_issuer_institution_name (issuer_institution_name(255)),
    INDEX idx_wealth_issuer_institution_type (wealth_issuer_institution_type),
    INDEX idx_product_risk_level (product_risk_level),
    INDEX idx_target_customer_type (target_customer_type),
    INDEX idx_product_operation_mode (product_operation_mode),
    INDEX idx_product_management_mode (product_management_mode),
    INDEX idx_investment_manager_name (investment_manager_name),
    INDEX idx_open_mode (open_mode),
    INDEX idx_fundraising_start_date (fundraising_start_date),
    INDEX idx_fundraising_end_date (fundraising_end_date),
    INDEX idx_product_actual_termination_date (product_actual_termination_date),
    INDEX idx_wealth_product_status (wealth_product_status),
    INDEX idx_new_old_product_flag (new_old_product_flag),
    INDEX idx_collection_date (collection_date),
    INDEX idx_data_owner_dept (data_owner_dept),
    INDEX idx_data_source_system (data_source_system),
    INDEX idx_created_at (created_at),
    INDEX idx_updated_at (updated_at)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='理财产品业务表';