import { gql } from '@apollo/client';

export const USABLE_DATA_SOURCES = gql`
  query UsableDataSources {
    usableDataSource {
      type
      requiredProperties
    }
  }
`;

export const LIST_DATA_SOURCE_TABLES = gql`
  query ListDataSourceTables {
    listDataSourceTables {
      name
      columns {
        name
        type
      }
    }
  }
`;

export const AUTO_GENERATED_RELATIONS = gql`
  query AutoGeneratedRelations($where: AutoGenerateInput) {
    autoGenerateRelation(where: $where) {
      from {
        tableName
        columnName
      }
      to {
        tableName
        columnName
      }
      type
    }
  }
`;

export const SAVE_DATA_SOURCE = gql`
  mutation SaveDataSource($data: DataSourceInput!) {
    saveDataSource(data: $data) {
      type
      properties
    }
  }
`;
