import * as Types from './__types__';

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type UsableDataSourcesQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type UsableDataSourcesQuery = { __typename?: 'Query', usableDataSource: Array<{ __typename?: 'UsableDataSource', type: Types.DataSourceName, requiredProperties: Array<string> }> };

export type ListDataSourceTablesQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type ListDataSourceTablesQuery = { __typename?: 'Query', listDataSourceTables: Array<{ __typename?: 'CompactTable', name: string, columns: Array<{ __typename?: 'CompactColumn', name: string, type: string }> }> };

export type AutoGeneratedRelationsQueryVariables = Types.Exact<{
  where?: Types.InputMaybe<Types.AutoGenerateInput>;
}>;


export type AutoGeneratedRelationsQuery = { __typename?: 'Query', autoGenerateRelation: Array<{ __typename?: 'Relation', type: Types.RelationType, from: { __typename?: 'RelationColumnInformation', tableName: string, columnName: string }, to: { __typename?: 'RelationColumnInformation', tableName: string, columnName: string } }> };

export type SaveDataSourceMutationVariables = Types.Exact<{
  data: Types.DataSourceInput;
}>;


export type SaveDataSourceMutation = { __typename?: 'Mutation', saveDataSource: { __typename?: 'DataSource', type: Types.DataSourceName, properties: any } };


export const UsableDataSourcesDocument = gql`
    query UsableDataSources {
  usableDataSource {
    type
    requiredProperties
  }
}
    `;

/**
 * __useUsableDataSourcesQuery__
 *
 * To run a query within a React component, call `useUsableDataSourcesQuery` and pass it any options that fit your needs.
 * When your component renders, `useUsableDataSourcesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useUsableDataSourcesQuery({
 *   variables: {
 *   },
 * });
 */
export function useUsableDataSourcesQuery(baseOptions?: Apollo.QueryHookOptions<UsableDataSourcesQuery, UsableDataSourcesQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<UsableDataSourcesQuery, UsableDataSourcesQueryVariables>(UsableDataSourcesDocument, options);
      }
export function useUsableDataSourcesLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<UsableDataSourcesQuery, UsableDataSourcesQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<UsableDataSourcesQuery, UsableDataSourcesQueryVariables>(UsableDataSourcesDocument, options);
        }
export type UsableDataSourcesQueryHookResult = ReturnType<typeof useUsableDataSourcesQuery>;
export type UsableDataSourcesLazyQueryHookResult = ReturnType<typeof useUsableDataSourcesLazyQuery>;
export type UsableDataSourcesQueryResult = Apollo.QueryResult<UsableDataSourcesQuery, UsableDataSourcesQueryVariables>;
export const ListDataSourceTablesDocument = gql`
    query ListDataSourceTables {
  listDataSourceTables {
    name
    columns {
      name
      type
    }
  }
}
    `;

/**
 * __useListDataSourceTablesQuery__
 *
 * To run a query within a React component, call `useListDataSourceTablesQuery` and pass it any options that fit your needs.
 * When your component renders, `useListDataSourceTablesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useListDataSourceTablesQuery({
 *   variables: {
 *   },
 * });
 */
export function useListDataSourceTablesQuery(baseOptions?: Apollo.QueryHookOptions<ListDataSourceTablesQuery, ListDataSourceTablesQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<ListDataSourceTablesQuery, ListDataSourceTablesQueryVariables>(ListDataSourceTablesDocument, options);
      }
export function useListDataSourceTablesLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ListDataSourceTablesQuery, ListDataSourceTablesQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<ListDataSourceTablesQuery, ListDataSourceTablesQueryVariables>(ListDataSourceTablesDocument, options);
        }
export type ListDataSourceTablesQueryHookResult = ReturnType<typeof useListDataSourceTablesQuery>;
export type ListDataSourceTablesLazyQueryHookResult = ReturnType<typeof useListDataSourceTablesLazyQuery>;
export type ListDataSourceTablesQueryResult = Apollo.QueryResult<ListDataSourceTablesQuery, ListDataSourceTablesQueryVariables>;
export const AutoGeneratedRelationsDocument = gql`
    query AutoGeneratedRelations($where: AutoGenerateInput) {
  autoGenerateRelation(where: $where) {
    from {
      tableName
      columnName
    }
    to {
      tableName
      columnName
    }
    type
  }
}
    `;

/**
 * __useAutoGeneratedRelationsQuery__
 *
 * To run a query within a React component, call `useAutoGeneratedRelationsQuery` and pass it any options that fit your needs.
 * When your component renders, `useAutoGeneratedRelationsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useAutoGeneratedRelationsQuery({
 *   variables: {
 *      where: // value for 'where'
 *   },
 * });
 */
export function useAutoGeneratedRelationsQuery(baseOptions?: Apollo.QueryHookOptions<AutoGeneratedRelationsQuery, AutoGeneratedRelationsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<AutoGeneratedRelationsQuery, AutoGeneratedRelationsQueryVariables>(AutoGeneratedRelationsDocument, options);
      }
export function useAutoGeneratedRelationsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<AutoGeneratedRelationsQuery, AutoGeneratedRelationsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<AutoGeneratedRelationsQuery, AutoGeneratedRelationsQueryVariables>(AutoGeneratedRelationsDocument, options);
        }
export type AutoGeneratedRelationsQueryHookResult = ReturnType<typeof useAutoGeneratedRelationsQuery>;
export type AutoGeneratedRelationsLazyQueryHookResult = ReturnType<typeof useAutoGeneratedRelationsLazyQuery>;
export type AutoGeneratedRelationsQueryResult = Apollo.QueryResult<AutoGeneratedRelationsQuery, AutoGeneratedRelationsQueryVariables>;
export const SaveDataSourceDocument = gql`
    mutation SaveDataSource($data: DataSourceInput!) {
  saveDataSource(data: $data) {
    type
    properties
  }
}
    `;
export type SaveDataSourceMutationFn = Apollo.MutationFunction<SaveDataSourceMutation, SaveDataSourceMutationVariables>;

/**
 * __useSaveDataSourceMutation__
 *
 * To run a mutation, you first call `useSaveDataSourceMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSaveDataSourceMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [saveDataSourceMutation, { data, loading, error }] = useSaveDataSourceMutation({
 *   variables: {
 *      data: // value for 'data'
 *   },
 * });
 */
export function useSaveDataSourceMutation(baseOptions?: Apollo.MutationHookOptions<SaveDataSourceMutation, SaveDataSourceMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<SaveDataSourceMutation, SaveDataSourceMutationVariables>(SaveDataSourceDocument, options);
      }
export type SaveDataSourceMutationHookResult = ReturnType<typeof useSaveDataSourceMutation>;
export type SaveDataSourceMutationResult = Apollo.MutationResult<SaveDataSourceMutation>;
export type SaveDataSourceMutationOptions = Apollo.BaseMutationOptions<SaveDataSourceMutation, SaveDataSourceMutationVariables>;