import { useEffect, useState } from 'react';
import { omit } from 'lodash';
import { Alert, Button, Popconfirm, Space, Spin, Typography } from 'antd';
import type { TableColumnsType } from 'antd';
import styled from 'styled-components';
import DeleteOutlined from '@ant-design/icons/DeleteOutlined';
import EditOutlined from '@ant-design/icons/EditOutlined';
import PlusOutlined from '@ant-design/icons/PlusOutlined';
import ModelRelationSelectionTable, {
  RelationsDataType,
} from '@/components/table/ModelRelationSelectionTable';
import { getJoinTypeText } from '@/utils/data';
import useModalAction from '@/hooks/useModalAction';
import RelationModal, {
  RelationFieldValue,
  RelationFormValues,
} from '@/components/modals/RelationModal';
import { convertFormValuesToIdentifier } from '@/hooks/useCombineFieldOptions';

const { Paragraph, Text, Title } = Typography;

const relationKeys = ['name', 'isAutoGenerated'];

const PageSection = styled.div`
  display: flex;
  flex-direction: column;
  gap: 22px;
`;

const HeaderMeta = styled.div`
  display: flex;
  flex-direction: column;
  gap: 8px;
  max-width: 840px;
`;

const Badge = styled.div`
  width: fit-content;
  height: 30px;
  padding: 0 12px;
  border-radius: 999px;
  background: rgba(111, 71, 255, 0.08);
  color: #6f47ff;
  font-size: 12px;
  font-weight: 700;
  display: inline-flex;
  align-items: center;
`;

const Panel = styled.div`
  border-radius: 24px;
  border: 1px solid rgba(15, 23, 42, 0.08);
  background: #fff;
  box-shadow: 0 22px 48px rgba(15, 23, 42, 0.05);
  padding: 22px;
`;

const FooterRow = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
`;

const LightButton = styled(Button)`
  &.ant-btn {
    min-width: 132px;
    height: 46px;
    border-radius: 14px;
    border: 0;
    background: #f2f4f8;
    color: #4f5565;
    font-weight: 700;
    box-shadow: none;
  }
`;

const TextButton = styled(Button)`
  &.ant-btn {
    min-width: 132px;
    height: 46px;
    border-radius: 14px;
    border: 0;
    background: transparent;
    color: #6f7688;
    font-weight: 700;
    box-shadow: none;
  }
`;

const PrimaryButton = styled(Button)`
  &.ant-btn {
    min-width: 132px;
    height: 46px;
    border-radius: 14px;
    border: 0;
    background: linear-gradient(180deg, #8c61ff 0%, #6f47ff 100%);
    color: #fff;
    font-weight: 700;
    box-shadow: 0 14px 30px rgba(111, 71, 255, 0.24);
  }
`;

export interface SelectedRecommendRelations {
  [modelName: string]: RelationsDataType[];
}

interface Props {
  fetching: boolean;
  recommendRelations: SelectedRecommendRelations;
  recommendNameMapping: Record<string, string>;
  onNext: (data: { relations: SelectedRecommendRelations }) => void;
  onBack: () => void;
  onSkip: () => void;
  submitting: boolean;
}

interface EditableRelationTableProps {
  index: number;
  modelName: string;
  onSetRelation: (payload: {
    modelName: string;
    defaultValue?: RelationsDataType;
  }) => void;
  onDeleteRow: (modelName: string, selectedRelation: RelationsDataType) => void;
  relations: RelationsDataType[];
  recommendNameMapping: Record<string, string>;
}

type SelectedRelationState = {
  modelName: string;
  defaultValue?: RelationsDataType;
};

function EditableRelationTable(props: EditableRelationTableProps) {
  const {
    index,
    modelName,
    onSetRelation,
    onDeleteRow,
    relations,
    recommendNameMapping,
  } = props;

  const columns: TableColumnsType<RelationsDataType> = [
    {
      title: '起始字段',
      dataIndex: 'fromField',
      key: 'fromField',
      render: (fromField) => `${fromField.modelName}.${fromField.fieldName}`,
      width: '35%',
    },
    {
      title: '目标字段',
      dataIndex: 'toField',
      key: 'toField',
      render: (toField) => `${toField.modelName}.${toField.fieldName}`,
      width: '35%',
    },
    {
      title: '关系类型',
      dataIndex: 'type',
      key: 'type',
      render: (type, relation) => (
        <>
          {getJoinTypeText(type)}
          {relation.isAutoGenerated && (
            <Text className="pl-1" type="secondary">
              （系统推荐）
            </Text>
          )}
        </>
      ),
      width: '30%',
    },
    {
      title: '',
      key: 'action',
      width: 72,
      align: 'center',
      render: (_, record) => (
        <Space size={16}>
          <EditOutlined
            onClick={() =>
              onSetRelation({
                modelName,
                defaultValue: record,
              })
            }
          />
          <Popconfirm
            title="确认删除这条关系吗？"
            okText="删除"
            okButtonProps={{ danger: true }}
            onConfirm={() => onDeleteRow(modelName, record)}
          >
            <DeleteOutlined />
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div>
      <ModelRelationSelectionTable
        columns={columns}
        dataSource={relations}
        tableTitle={recommendNameMapping[modelName]}
        extra={(onCollapseOpen) => (
          <Button
            onClick={(event) => {
              onSetRelation({ modelName });
              onCollapseOpen(event, recommendNameMapping[modelName]);
            }}
            size="small"
            title="添加关系"
          >
            <PlusOutlined />
            添加
          </Button>
        )}
        rowKey={(record: RelationsDataType) =>
          `${modelName}-${record.fromField.fieldName}-${record.toField.modelName}-${record.toField.fieldName}-${index}`
        }
      />
    </div>
  );
}

export default function DefineRelations(props: Props) {
  const {
    fetching,
    recommendRelations,
    recommendNameMapping,
    onBack,
    onNext,
    onSkip,
    submitting,
  } = props;

  const [relations, setRelations] =
    useState<SelectedRecommendRelations>(recommendRelations);

  const [selectedRelation, setSelectedRelation] =
    useState<SelectedRelationState | null>(null);

  const [showNoRecommendationAlert, setShowNoRecommendationAlert] =
    useState<boolean>(false);

  useEffect(() => {
    setRelations(recommendRelations);

    const recommendRelationsValues = Object.values(recommendRelations);
    if (recommendRelationsValues.length === 0) return;

    const allEmpty = recommendRelationsValues.every(
      (value) => value.length === 0,
    );
    setShowNoRecommendationAlert(allEmpty);
  }, [recommendRelations]);

  const relationModal = useModalAction();

  const isRecommendRelation = (
    modelName: string,
    relation: RelationsDataType,
  ) => {
    const isOriginalRelation = (recommendRelations[modelName] || []).find(
      (originalRelation) =>
        JSON.stringify(omit(originalRelation, relationKeys)) ===
        JSON.stringify(omit(relation, relationKeys)),
    );

    return isOriginalRelation?.isAutoGenerated || false;
  };

  const onAddRelation = (relationFormValues: RelationFormValues) => {
    const relation = convertFormValuesToIdentifier(relationFormValues);
    const modelName = relation.fromField.modelName;
    const isAutoGenerated = isRecommendRelation(modelName, relation);
    const newRelations = {
      ...relations,
      [modelName]: [
        ...(relations[modelName] || []),
        { ...relation, isAutoGenerated },
      ],
    };
    setRelations(newRelations);
  };

  const onCloseModal = () => {
    setSelectedRelation(null);
    relationModal.closeModal();
  };

  const onDeleteRow = (
    modelName: string,
    selectedRelation: RelationsDataType,
  ) => {
    const newRelations = {
      ...relations,
      [modelName]: relations[modelName].filter(
        (relation) =>
          JSON.stringify(relation) !== JSON.stringify(selectedRelation),
      ),
    };
    setRelations(newRelations);
  };

  const onSetRelation = (payload: SelectedRelationState) => {
    setSelectedRelation(payload);
    relationModal.openModal();
  };

  const onUpdateRelation = (
    modelName: string,
    originalRelationValue: RelationsDataType,
    newRelationValue: RelationFormValues,
  ) => {
    const newRelation = convertFormValuesToIdentifier(newRelationValue);
    const isAutoGenerated = isRecommendRelation(modelName, newRelation);
    const newRelations = {
      ...relations,
      [modelName]: relations[modelName].map((relation) => {
        if (
          JSON.stringify(relation) === JSON.stringify(originalRelationValue)
        ) {
          return { ...newRelation, isAutoGenerated };
        }
        return relation;
      }),
    };

    setRelations(newRelations);
  };

  const submit = () => {
    onNext && onNext({ relations });
  };

  return (
    <PageSection>
      <HeaderMeta>
        <Badge>Step 3 / 定义关系</Badge>
        <Title level={2} style={{ margin: 0, fontSize: 30 }}>
          定义资产关系
        </Title>
        <Paragraph style={{ marginBottom: 0, fontSize: 15, lineHeight: 1.8 }}>
          你可以为已选择的资产建立关系。系统会基于主键、外键自动给出推荐关系，并把最终确认的关系写入语义模型。
        </Paragraph>
      </HeaderMeta>

      {showNoRecommendationAlert && (
        <Alert
          message="暂无推荐关系"
          description="当前没有检测到主键或外键，因此还无法生成推荐关系。你可以手动补充。"
          type="info"
          showIcon
        />
      )}

      <Panel>
        {Object.entries(relations).map(
          ([modelReferenceName, relations = []], index) => (
            <EditableRelationTable
              key={`${modelReferenceName}-${relations.length}`}
              index={index}
              modelName={modelReferenceName}
              relations={relations}
              onSetRelation={onSetRelation}
              onDeleteRow={onDeleteRow}
              recommendNameMapping={recommendNameMapping}
            />
          ),
        )}
        <div style={{ padding: '18px 0 4px', textAlign: 'center' }}>
          <Spin spinning={fetching} tip="加载中…" />
        </div>
      </Panel>

      <FooterRow>
        <Text type="secondary" style={{ fontSize: 13 }}>
          关系确认后会直接进入建模工作台。你也可以先跳过，后续再在建模页继续补充。
        </Text>
        <Space size={12}>
          <LightButton onClick={onBack}>返回</LightButton>
          <TextButton onClick={onSkip} disabled={submitting}>
            跳过这一步
          </TextButton>
          <PrimaryButton
            type="primary"
            onClick={submit}
            loading={submitting}
            disabled={fetching}
            data-ph-capture="true"
            data-ph-capture-attribute-name="cta_finish_define_relationship"
          >
            完成配置
          </PrimaryButton>
        </Space>
      </FooterRow>
      <RelationModal
        {...relationModal.state}
        model={selectedRelation?.modelName || ''}
        relations={relations}
        onSubmit={async (values) => {
          if (selectedRelation?.defaultValue) {
            onUpdateRelation(
              selectedRelation.modelName,
              selectedRelation.defaultValue,
              values,
            );
          } else {
            onAddRelation(values);
          }
          setSelectedRelation(null);
        }}
        onClose={onCloseModal}
        defaultValue={
          selectedRelation?.defaultValue
            ? (omit(
                selectedRelation.defaultValue,
                relationKeys,
              ) as RelationFieldValue)
            : undefined
        }
      />
    </PageSection>
  );
}
