import { useState } from 'react';
import Link from 'next/link';
import { omit } from 'lodash';
import { Button, Col, Popconfirm, Row, Space, Typography } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import DeleteOutlined from '@ant-design/icons/DeleteOutlined';
import EditOutlined from '@ant-design/icons/EditOutlined';
import PlusOutlined from '@ant-design/icons/PlusOutlined';
import ModelRelationSelectionTable, {
  RelationsDataType,
} from '@/components/table/ModelRelationSelectionTable';
import { columns as defaultColumns } from '@/components/pages/setup/RecommendRelations';
import useModalAction from '@/hooks/useModalAction';
import AddRelationModal from '@/components/modals/AddRelationModal';

const { Title, Text } = Typography;

export interface SelectedRecommendRelations {
  [modelName: string]: RelationsDataType[];
}

interface Props {
  selectedRecommendRelations: SelectedRecommendRelations;
  onNext: (data: { relations: SelectedRecommendRelations }) => void;
  onBack: () => void;
}

interface EditableRelationTableProps {
  index: number;
  modelName: string;
  onSetRelation: (payload: {
    modelName: string;
    defaultValue?: RelationsDataType;
  }) => void;
  onDeleteRow: (modelName: string, selectedRelation: RelationsDataType) => void;
  relations: RelationsDataType[];
}

function EditableRelationTable(props: EditableRelationTableProps) {
  const { index, modelName, onSetRelation, onDeleteRow, relations } = props;

  const columns: ColumnsType<RelationsDataType> = [
    ...defaultColumns,
    {
      title: '',
      key: 'action',
      width: 48,
      align: 'center',
      render: (_, record) => (
        <Space size={[16, 0]}>
          <EditOutlined
            onClick={() =>
              onSetRelation({
                modelName,
                defaultValue: record,
              })
            }
          />
          <Popconfirm
            title="Sure to delete?"
            okText="Delete"
            okButtonProps={{ danger: true }}
            onConfirm={() => onDeleteRow(modelName, record)}
          >
            <DeleteOutlined />
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div className="mt-6">
      <ModelRelationSelectionTable
        columns={columns}
        dataSource={relations}
        tableTitle={modelName}
        extra={(onCollapseOpen) => (
          <Button
            onClick={(event) => {
              onSetRelation({ modelName });
              onCollapseOpen(event, modelName);
            }}
            size="small"
            title="Add relation"
          >
            <PlusOutlined />
            Add relation
          </Button>
        )}
        rowKey={(record: RelationsDataType) =>
          `${modelName}-${record.name}-${index}`
        }
      />
    </div>
  );
}

export default function DefineRelations(props: Props) {
  const { selectedRecommendRelations, onBack, onNext } = props;

  const [relations, setRelations] = useState<SelectedRecommendRelations>(
    selectedRecommendRelations
  );

  const [selectedRelation, setSelectedRelation] = useState<{
    modelName: string;
    defaultValue?: RelationsDataType;
  }>(null);

  const addRelationModal = useModalAction();

  // check is the relation is auto-generated or not
  const isRecommendRelation = (
    modelName: string,
    relation: RelationsDataType
  ) => {
    const isOriginalRelation = (
      selectedRecommendRelations[modelName] || []
    ).find(
      (originalRelation) =>
        JSON.stringify(omit(originalRelation, ['isAutoGenerated'])) ===
        JSON.stringify(relation)
    );
    return isOriginalRelation?.isAutoGenerated || false;
  };

  const onAddRelation = (modelName: string, relation: RelationsDataType) => {
    const isAutoGenerated = isRecommendRelation(modelName, relation);
    const newRelations = {
      ...relations,
      [modelName]: [
        ...(relations[modelName] || []),
        { ...relation, isAutoGenerated },
      ],
    };
    setRelations(newRelations);
  };

  const onCloseModal = () => {
    setSelectedRelation(null);
    addRelationModal.closeModal();
  };

  const onDeleteRow = (
    modelName: string,
    selectedRelation: RelationsDataType
  ) => {
    const newRelations = {
      ...relations,
      [modelName]: relations[modelName].filter(
        (relation) =>
          JSON.stringify(relation) !== JSON.stringify(selectedRelation)
      ),
    };
    setRelations(newRelations);
  };

  const onSetRelation = (payload: {
    modelName: string;
    defaultValue?: RelationsDataType;
  }) => {
    setSelectedRelation(payload);
    addRelationModal.openModal();
  };

  const onUpdateRelation = (
    modelName: string,
    originalRelationValue: RelationsDataType,
    newRelationValue: RelationsDataType
  ) => {
    const isAutoGenerated = isRecommendRelation(modelName, newRelationValue);

    const newRelations = {
      ...relations,
      [modelName]: relations[modelName].map((relation) => {
        if (
          JSON.stringify(relation) === JSON.stringify(originalRelationValue)
        ) {
          return { ...newRelationValue, isAutoGenerated };
        }
        return relation;
      }),
    };
    setRelations(newRelations);
  };

  const submit = () => {
    onNext && onNext({ relations });
  };

  return (
    <div>
      <Title level={1} className="mb-3">
        Define the relations
      </Title>
      <Text>
        After creating your data models in step 2, you can specify how they
        should be joined together by defining the relationships. We will
        automatically create the relations based on the 'primary' and 'foreign'
        in your data sources.{` `}
        <Link href="" target="_blank" rel="noopener noreferrer">
          Learn more
        </Link>
      </Text>
      <div className="my-6">
        {Object.entries(relations).map(([modelName, relations = []], index) => (
          <EditableRelationTable
            key={`${modelName}-${relations.length}`}
            index={index}
            modelName={modelName}
            relations={relations}
            onSetRelation={onSetRelation}
            onDeleteRow={onDeleteRow}
          />
        ))}
      </div>
      <Row gutter={16} className="pt-6">
        <Col span={12}>
          <Button onClick={onBack} size="large" block>
            Back
          </Button>
        </Col>
        <Col className="text-right" span={12}>
          <Button type="primary" size="large" block onClick={submit}>
            Next
          </Button>
        </Col>
      </Row>
      <AddRelationModal
        model={selectedRelation?.modelName}
        {...addRelationModal.state}
        onSubmit={async (values) => {
          if (selectedRelation?.defaultValue) {
            onUpdateRelation(
              selectedRelation.modelName,
              selectedRelation.defaultValue,
              values
            );
          } else {
            onAddRelation(values.fromField.model, values);
          }
          setSelectedRelation(null);
        }}
        onClose={onCloseModal}
        allowSetDescription={false}
        defaultValue={
          selectedRelation?.defaultValue
            ? omit(selectedRelation.defaultValue, ['isAutoGenerated'])
            : undefined
        }
      />
    </div>
  );
}
