name: Providers Setup Release Image

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Docker image tag name (Optional)
        type: string

# Not sure the name is correct in env
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/wren-setup-provider-ui  # push to my docker hub

jobs:
  build:
    strategy:
      matrix:
        arch:
          - runner: ubuntu-latest
            platform: linux/amd64
          - runner: linux_arm64_runner
            platform: linux/arm64
    runs-on: ${{ matrix.arch.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare tag
        id: tag
        run: |
          if [ -n "${{ github.event.inputs.tag_name }}" ]; then
            echo "TAG=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          else
            echo "TAG=commit-$(git log -1 --pretty=%h)" >> $GITHUB_ENV
          fi

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./wren-ai-service/tools/providers-setup
          file: ./wren-ai-service/tools/providers-setup/Dockerfile
          platforms: ${{ matrix.arch.platform }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
