# create the github action to run the yarn lint when PR created or pushed to main branch
#

name: Wren-UI Lint

on:
  push:
    paths:
      - 'wren-ui/**'
  pull_request:
    types: [ labeled ]

permissions:
  contents: read

concurrency:
  # avoid mis-canceling the ci runs while other labels are added to the PR, so we add the label name as the condition
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.label.name == 'ci/ui' && github.event.number || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: wren-ui

jobs:
  eslint:
     # run this job only if the PR is labeled with "ci/ui"
    if: ${{ github.event.label.name == 'ci/ui' || github.event_name == 'push'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Node.js dependencies
        run: yarn install
      # ESLint and Prettier must be in `package.json`
      - name: Run ESLint
        uses: samuelmeuli/lint-action@v1
        with:
          eslint: true
          auto_fix: true
          eslint_extensions: js,jsx,ts,tsx