# create the github action to run the yarn lint when PR created or pushed to main branch
#

name: Wren-UI Lint

on:
  pull_request:
    types: [ labeled ]
    # epic/* is for epic feature
    branches: [ main, epic/*, feature/* ]
  push:

permissions:
  contents: read

concurrency:
  # avoid mis-canceling the ci runs while other labels are added to the PR, so we add the label name as the condition
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.label.name == 'ci/ui' && github.event.number || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: wren-ui

jobs:
  eslint:
     # run this job only if the PR is labeled with "ci/ui"
    if: ${{ github.event.label.name == 'ci/ui' }}
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3 #use v3 for action-yarn v4
        with:
          node-version: 16.x
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Node.js dependencies
        run: yarn install
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          auto_fix: true
          eslint_extensions: js,jsx,ts,tsx