name: Wren Launcher CI

on:
  pull_request:
    types: [synchronize, labeled]
    paths:
      - 'wren-launcher/**'
      - '.github/workflows/wren-launcher-ci.yaml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.number || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: wren-launcher

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache-dependency-path: wren-launcher/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.3.1
          working-directory: wren-launcher

  fmt-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache-dependency-path: wren-launcher/go.sum
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Download dependencies
        run: go mod download
      - name: Run format check
        run: |
          make fmt
          # Check if there are any formatting changes
          if [ -n "$(git diff --name-only)" ]; then
            echo "Code is not formatted properly. Please run 'make fmt' and commit the changes."
            git diff
            exit 1
          fi
      - name: Run go vet
        run: make vet
      - name: Run tests
        run: go test ./commands/dbt

  security-scan:
    runs-on: ubuntu-latest
    needs: fmt-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache-dependency-path: wren-launcher/go.sum
      - name: Run Gosec Security Scanner
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec ./...
      - name: Run Go mod audit
        run: |
          go mod verify
          go list -json -deps ./... | jq -r '.Module | select(.Version) | "\(.Path) \(.Version)"' | sort -u
